// ── Approved marketing frames ─────────────────────────────────────────────
// The 7 approved App Store marketing screenshots (1284×2778 PNG originals in
// /public/marketing/onis-final). Static imports give next/image the intrinsic
// width/height (no layout shift) and let the optimizer serve responsive
// AVIF/WebP variants. The originals are never edited — each frame's baked
// headline band is hidden by presentation cropping only (FrameArtwork), so
// the HTML headline is the single visible headline per section.
//
// visibleH — fraction of the frame's height shown in the artwork window.
// focusY   — object-position Y (0..1) selecting which part of the frame the
//            window shows (1 = bottom-anchored).
// bg       — the frame's own baked background color, used as the card surface
//            so any residual letterboxing is invisible.

import type { StaticImageData } from "next/image";
import trackBeforeYouForget from "../../public/marketing/onis-final/track-before-you-forget.png";
import oneTapFromYourWrist from "../../public/marketing/onis-final/one-tap-from-your-wrist.png";
import heroPairComposite from "../../public/marketing/onis-final/hero-pair.png";
import yourHabitsOneGlanceAway from "../../public/marketing/onis-final/your-habits-one-glance-away.png";
import buildReduceUnderstand from "../../public/marketing/onis-final/build-reduce-understand.png";
import builtForYourWrist from "../../public/marketing/onis-final/built-for-your-wrist.png";
import stopGuessingSeeThePattern from "../../public/marketing/onis-final/stop-guessing-see-the-pattern.png";
import aCalmerNextStep from "../../public/marketing/onis-final/a-calmer-next-step.png";

export interface MarketingFrame {
  image: StaticImageData;
  alt: string;
  bg: string;
  visibleH: number;
  focusY: number;
}

// The two hero frames share identical visibleH/focusY so their rendered
// heights match exactly and the cropped iPhone continues across the seam.
// heroPair is the two approved frames stitched edge-to-edge into ONE image
// (pixels untouched — generated by drawing both originals side by side), so
// the desktop pair resamples continuously with no seam by construction.
export const frames = {
  heroPair: {
    image: heroPairComposite,
    alt: "The ONIS Today screen on a cropped iPhone continuing into an Apple Watch logging Coffee with one tap — 2 cups logged, 2 cups left.",
    bg: "#f7e9da",
    visibleH: 0.84,
    focusY: 1,
  },
  track: {
    image: trackBeforeYouForget,
    alt: "The ONIS Today screen on iPhone: Coffee at 2 of 4 cups with day-by-day progress rings, plus Drink water, Read, Study, and Plan tomorrow trackers.",
    bg: "#f6e7d6",
    visibleH: 0.84,
    focusY: 1,
  },
  wrist: {
    image: oneTapFromYourWrist,
    alt: "An Apple Watch logging Coffee with a +1 button — 2 cups logged, 2 cups left — beside the same iPhone Today screen.",
    bg: "#f8ecdf",
    visibleH: 0.84,
    focusY: 1,
  },
  widgets: {
    image: yourHabitsOneGlanceAway,
    alt: "ONIS widgets on the iPhone Home Screen showing Drink water, Coffee, and Read progress with one-tap +1, Start, and Done actions.",
    bg: "#eae7f1",
    visibleH: 0.74,
    focusY: 0.78,
  },
  modes: {
    image: buildReduceUnderstand,
    alt: "Three ONIS tracker cards: Build with Drink water and Read, Reduce with Coffee at 2 of 4 cups, and Understand with a daily Mood check-in.",
    bg: "#efe9da",
    visibleH: 0.58,
    focusY: 0.48,
  },
  watchTrio: {
    image: builtForYourWrist,
    alt: "Three Apple Watch screens: the ONIS tracker list, a running Read timer at 7:55 with pause and stop, and Plan tomorrow marked done.",
    bg: "#eeeae0",
    visibleH: 0.32,
    focusY: 0.59,
  },
  trends: {
    image: stopGuessingSeeThePattern,
    alt: "The ONIS Trends screen: Coffee at 2 cups logged of a 4-cup limit, 2.4 daily average, 5 days at or under, 17 percent below the prior period, and activity by day.",
    bg: "#f7e9d9",
    visibleH: 0.64,
    focusY: 0.9,
  },
  coach: {
    image: aCalmerNextStep,
    alt: "The ONIS Coach screen for Coffee: within a 4-cup limit at 2 cups, a short what-to-know summary, and one clear next step.",
    bg: "#f5e8c9",
    visibleH: 0.7,
    focusY: 0.84,
  },
} as const satisfies Record<string, MarketingFrame>;

// Intrinsic dimensions of every approved frame (verified with sips).
export const FRAME_WIDTH = 1284;
export const FRAME_HEIGHT = 2778;
